--ROLLBACK ADD-RATINGS

ALTER TABLE ProductRatings DROP CONSTRAINT FK_Product_ProductRatings
DROP TABLE ProductRatings
GO

--ROLLBACK ADD-CATEGORIES

ALTER TABLE Products DROP CONSTRAINT [FK_Products_Categories] 
ALTER TABLE PRODUCTS DROP COLUMN Category_Id
DROP TABLE Categories
GO

--Rollback INITIAL-SCHEMA

DROP TABLE PRODUCTS
GO