--BEGIN TRANSACTION

CREATE TABLE ProductRatings (Id INT IDENTITY(1, 1) NOT NULL, Rating INT, Comment VARCHAR(255), Product_Id INT NOT NULL, 
	CONSTRAINT PK_ProductRatings PRIMARY KEY(Id), 
	CONSTRAINT FK_Product_ProductRatings FOREIGN KEY (Product_Id)
		REFERENCES [Products] (Id) ON DELETE CASCADE)
GO

--ROLLBACK
--COMMIT