--BEGIN TRANSACTION

CREATE TABLE Categories (Id INT IDENTITY(1, 1) NOT NULL, [Type] VARCHAR(55),
	CONSTRAINT PK_Categories PRIMARY KEY(Id))
GO

ALTER TABLE [Products] ADD [Category_Id] INT
GO
ALTER TABLE [Products] WITH CHECK ADD  CONSTRAINT [FK_Products_Categories] FOREIGN KEY(Category_Id)
REFERENCES [Categories] (Id) ON DELETE CASCADE
GO

--ROLLBACK
--COMMIT