--BEGIN TRANSACTION

CREATE TABLE Products (Id INT IDENTITY(1, 1) NOT NULL, [Name] VARCHAR(55), Price DECIMAL NOT NULL, 
	CONSTRAINT PK_Products PRIMARY KEY(Id))
CREATE TABLE Categories (Id INT IDENTITY(1, 1) NOT NULL, [Type] VARCHAR(55),
	CONSTRAINT PK_Categories PRIMARY KEY(Id))
GO

ALTER TABLE [Products] ADD [Category_Id] INT
GO
ALTER TABLE [Products] WITH CHECK ADD  CONSTRAINT [FK_Products_Categories] FOREIGN KEY(Category_Id)
REFERENCES [Categories] (Id) ON DELETE CASCADE
GO

CREATE TABLE ProductRatings (Id INT IDENTITY(1, 1) NOT NULL, Rating INT, Comment VARCHAR(255), Product_Id INT NOT NULL, 
	CONSTRAINT PK_ProductRatings PRIMARY KEY(Id), 
	CONSTRAINT FK_Product_ProductRatings FOREIGN KEY (Product_Id)
		REFERENCES [Products] (Id) ON DELETE CASCADE)

--ROLLBACK
--COMMIT